### ISSUE TITLE
NFR1: Security

### ISSUE THREAD

**Issue by Jarred-C** [WSU-4110/LAN-party-backend#16]
NFR1: Security
-
Goal: Making sure a user’s data is accessible only by them, unless otherwise authorized.
-
Stakeholders: All
-
By keeping private data private, a user is able to maintain the integrity of the information stored in their profile, as well as their email and password. Whether done by encryption of some sort or cookies has yet to be decided.
-
Origin: This was discussed during a scrum meeting by all members.
-
Version: 1.0 | Date: 9/28/2020 | Priority: 1
-

**Comment by ga2599** [comment]
sign in function provides password security

**Comment by ga2599** [comment]
Although we have hashed passwords we want to implement tokens first before we satisfy this requirement. Moving to sprint 2 for further work.

**Comment by ga2599** [comment]
Hashed passwords allows for protection of user data. Not visible to anyone who has access to the DB nor the front-end.
