### ISSUE TITLE
FR16: Host A Party

### ISSUE THREAD

**Issue by Jarred-C** [WSU-4110/LAN-party-backend#22]
-
FR16: Host A Party
-
Goal: Users can create LAN parties for others to attend
-
Users can create parties, including setting its locations, send invites
-
Origin: its the entire point of the application
-
Version: 1.0 | Date: 9/11/2020 | Priority: 1
-

**Comment by Jarred-C** [comment]
On my branch in handlers/party and services/PartyAPI. Please review.

**Comment by ga2599** [comment]
reviewed and merged. nice work!
