### ISSUE TITLE
FR8: Create Account

### ISSUE THREAD

**Issue by Jarred-C** [WSU-4110/LAN-party-backend#8]
FR8: Create Account
-
Goal: User can create their account
-
Stakeholders: Gamers / Party Hosts
-
A user opens the app and registers an account by inputting their information and linking their other accounts so they can set up their LAN Party account more easily.
-
Origin: Obviously necessary so that we can store different users and have their data separate from others
-
Version: 1.0 | Date: 9/11/2020 | Priority: 1
-

**Comment by ga2599** [comment]
We have the backend completed. Can test with Insomnia and the front.
